Repository firebase/firebase-admin-python, pull requests merged in 2020-04, with the labels that each got.

#447 feat(ml): Adding Firebase ML management APIs
  .github/workflows/release.yml
  CONTRIBUTING.md
  firebase_admin/_utils.py
  firebase_admin/ml.py
  integration/test_ml.py
  tests/data/invalid_model.tflite
  tests/data/model1.tflite
  tests/test_ml.py
Labels: release:stage

#451 [chore] Release 4.1.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet

#453 [chore] Release 4.1.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet

#450 feat(auth): Adding multi-tenancy and IdP management APIs
  firebase_admin/_auth_client.py
  firebase_admin/_auth_providers.py
  firebase_admin/_auth_utils.py
  firebase_admin/_token_gen.py
  firebase_admin/_user_mgt.py
  firebase_admin/auth.py
  firebase_admin/tenant_mgt.py
  integration/test_auth.py
  integration/test_tenant_mgt.py
  snippets/auth/index.py
  tests/data/list_oidc_provider_configs.json
  tests/data/list_saml_provider_configs.json
  tests/data/oidc_provider_config.json
  tests/data/saml_provider_config.json
  tests/test_auth_providers.py
  tests/test_tenant_mgt.py
  tests/test_token_gen.py
  tests/test_user_mgt.py
Labels: release-note

#457 [chore] Release 4.2.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet
