Repository firebase/firebase-admin-python, pull requests merged in 2021-12, with the labels that each got.

#549 feat(auth): enables OIDC auth code flow
  firebase_admin/_auth_client.py
  firebase_admin/_auth_providers.py
  firebase_admin/auth.py
  integration/test_auth.py
  tests/test_auth_providers.py
Labels: release-note

#595 Fix OIDC integration tests
  integration/test_auth.py
Labels: release:stage

#596 [chore] Release 5.2.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet
