Repository firebase/firebase-admin-python, pull requests merged in 2021-04, with the labels that each got.

#542 change: Drop Python 3.5 support
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  integration/test_project_management.py
  requirements.txt
  setup.py
  tests/testutils.py
Labels: release-note, release:stage

#540 chore: Add nightly build workflow
  .github/workflows/nightly.yml
  integration/test_messaging.py
Labels: release:stage

#545 Remove failing integration test added for nightly
  integration/test_messaging.py
Labels: release:stage

#544 chore: Upgraded Google Auth, Cloud Firestore, and Cloud Storage dependencies
  requirements.txt
  setup.py
  tests/test_token_gen.py
Labels: release-note, release:stage

#541 fix: Using alg=none header for custom tokens in emulator mode
  firebase_admin/_token_gen.py
  tests/test_token_gen.py
Labels: release-note

#510 fix: Accept Path-like objects in credential factory functions
  firebase_admin/credentials.py
  tests/test_credentials.py
Labels: release-note

#547 [chore] Release 5.0.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet
