Repository firebase/firebase-admin-python, pull requests merged in 2022-08, with the labels that each got.

#629 feat(credentials): Add async credentials.
  firebase_admin/credentials.py
  integration/test_auth.py
  requirements.txt
Labels: release:stage

#636 Remove failing nightly tests in project_management
  integration/test_project_management.py
Labels: release:stage

#635 feat(firestore): Async Firestore
  firebase_admin/firestore_async.py
  integration/conftest.py
  integration/test_firestore_async.py
  requirements.txt
  snippets/firestore/__init__.py
  snippets/firestore/firestore.py
  snippets/firestore/firestore_async.py
  tests/test_firestore_async.py
Labels: api: firestore, release-note

#637 [chore] Release 5.3.0
  firebase_admin/__about__.py
Labels: release:publish, release:tweet
