Repository firebase/firebase-admin-python, pull requests merged in 2025-04, with the labels that each got.

#870 Added minimal support for sending FCM messages in async using HTTP/2
  firebase_admin/_utils.py
  firebase_admin/messaging.py
  integration/conftest.py
  integration/test_messaging.py
  requirements.txt
  setup.py
  tests/test_messaging.py
Labels: release:stage

#873 chore: Update README to deprecate Python 3.8 support
  README.md
Labels: release-note

#874 [chore] Release 6.8.0
  firebase_admin/__about__.py
Labels: release:stage, release:publish
