Repository firebase/firebase-admin-python, pull requests merged in 2025-07, with the labels that each got.

#896 fix(functions): Removed usage of deprecated `datetime.utcnow()`
  firebase_admin/functions.py
  tests/test_functions.py
Labels: release-note, release:stage

#897 chore: Upgraded Google API Core, Cloud Firestore, and Cloud Storage dependencies
  requirements.txt
  setup.py
Labels: release-note, release:stage

#884 feat(auth) Update `ActionCodeSettings` to support `link_domain` and deprecate `dynamic_link_domain`
  firebase_admin/_auth_utils.py
  firebase_admin/_user_mgt.py
  firebase_admin/auth.py
  tests/test_user_mgt.py
Labels: release-note

#903 [chore] Release 7.1.0
  firebase_admin/__about__.py
Labels: release:stage, release:publish
